name: FinanceApp
options:
  bundleIdPrefix: com.sergiofinance
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  developmentLanguage: en
  knownRegions:
    - en
    - es
    - pt-BR

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  FinanceApp:
    type: application
    platform: iOS
    sources:
      - path: FinanceApp
    settings:
      base:
        INFOPLIST_FILE: FinanceApp/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.sergiofinance.FinanceApp
        SWIFT_OBJC_BRIDGING_HEADER: "$(PROJECT_DIR)/FinanceApp/FinanceApp-Bridging-Header.h"
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/libs"
        LIBRARY_SEARCH_PATHS:
          - "$(PROJECT_DIR)/libs"
        OTHER_LDFLAGS:
          - "-lfinance_ffi"
          - "-lsqlite3"
          - "-lresolv"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 9QVQJF9N92
        CODE_SIGN_ENTITLEMENTS: FinanceApp/FinanceApp.entitlements
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
    dependencies:
      - target: FinanceWidgetExtension

  FinanceWidgetExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: FinanceWidgetExtension
      - path: FinanceApp/Models
      - path: FinanceApp/FFI
      - path: FinanceApp/Utils/CurrencyFormatter.swift
      - path: FinanceApp/Utils/DateUtils.swift
      - path: FinanceApp/Utils/L10n.swift
      - path: FinanceApp/Theme/AppTheme.swift
      - path: FinanceApp/Resources/en.lproj
        type: folder
        buildPhase: resources
      - path: FinanceApp/Resources/es.lproj
        type: folder
        buildPhase: resources
      - path: FinanceApp/Resources/pt-BR.lproj
        type: folder
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sergiofinance.FinanceApp.FinanceWidget
        SWIFT_OBJC_BRIDGING_HEADER: "$(PROJECT_DIR)/FinanceWidgetExtension/FinanceWidget-Bridging-Header.h"
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/libs"
        LIBRARY_SEARCH_PATHS:
          - "$(PROJECT_DIR)/libs"
        OTHER_LDFLAGS:
          - "-lfinance_ffi"
          - "-lsqlite3"
          - "-lresolv"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 9QVQJF9N92
        CODE_SIGN_ENTITLEMENTS: FinanceWidgetExtension/FinanceWidgetExtension.entitlements
        CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: "YES"
        INFOPLIST_FILE: FinanceWidgetExtension/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
