/* Generated by cbindgen — do not edit manually */

#ifndef FINANCE_FFI_H
#define FINANCE_FFI_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Initialize the database at the given path. Must be called before any other function.
 *
 * # Safety
 * `path` must be a valid C string pointer.
 */
char *init_database(const char *path);

/**
 * Create a new account.
 *
 * # Safety
 * All pointer parameters must be valid C strings.
 */
char *create_account(const char *user_id,
                     const char *name,
                     const char *currency);

/**
 * Create a new category.
 *
 * # Safety
 * All pointer parameters must be valid C strings.
 */
char *create_category(const char *user_id,
                      const char *name,
                      const char *icon);

/**
 * Seed default categories for a user if none exist yet.
 * Idempotent — returns existing categories if already seeded.
 *
 * # Safety
 * `user_id` must be a valid C string containing a UUID.
 */
char *seed_default_categories(const char *user_id);

/**
 * Create a new transaction.
 *
 * # Safety
 * All pointer parameters must be valid C strings.
 * `transaction_type` must be one of: "expense", "income", "transfer".
 * `amount` is in cents (integer).
 */
char *create_transaction(const char *account_id,
                         const char *category_id,
                         int64_t amount,
                         const char *transaction_type,
                         const char *description,
                         const char *date);

/**
 * Get the balance for an account (in cents).
 *
 * # Safety
 * `account_id` must be a valid C string containing a UUID.
 */
char *get_balance(const char *account_id);

/**
 * Get pending sync changes as JSON.
 */
char *get_pending_sync(void);

/**
 * Get spending aggregated by category for an account within a date range.
 *
 * # Safety
 * All pointer parameters must be valid C strings. Dates must be RFC3339 formatted.
 */
char *get_spending_by_category(const char *account_id,
                               const char *from,
                               const char *to);

/**
 * Get income vs expenses summary for an account within a date range.
 *
 * # Safety
 * All pointer parameters must be valid C strings. Dates must be RFC3339 formatted.
 */
char *get_income_vs_expenses(const char *account_id,
                             const char *from,
                             const char *to);

/**
 * Create a new recurring transaction.
 *
 * # Safety
 * All pointer parameters must be valid C strings.
 */
char *create_recurring_transaction(const char *account_id,
                                   const char *category_id,
                                   int64_t amount,
                                   const char *transaction_type,
                                   const char *description,
                                   const char *frequency,
                                   const char *start_date,
                                   const char *end_date);

/**
 * List recurring transactions for an account.
 *
 * # Safety
 * `account_id` must be a valid C string.
 */
char *list_recurring_transactions(const char *account_id);

/**
 * Delete a recurring transaction.
 *
 * # Safety
 * `id` must be a valid C string.
 */
char *delete_recurring_transaction(const char *id);

/**
 * Process due recurring transactions and create actual transactions.
 *
 * # Safety
 * This function is safe to call.
 */
char *process_due_recurring_transactions(void);

/**
 * Create a new budget.
 *
 * # Safety
 * All pointer parameters must be valid C strings. `category_id` can be null for account-wide budgets.
 */
char *create_budget(const char *account_id,
                    const char *category_id,
                    const char *name,
                    int64_t amount,
                    const char *period,
                    const char *start_date);

/**
 * List budgets for an account.
 *
 * # Safety
 * `account_id` must be a valid C string.
 */
char *list_budgets(const char *account_id);

/**
 * Delete a budget.
 *
 * # Safety
 * `id` must be a valid C string.
 */
char *delete_budget(const char *id);

/**
 * Get budget progress for a specific budget.
 *
 * # Safety
 * `budget_id` must be a valid C string.
 */
char *get_budget_progress(const char *budget_id);

/**
 * Seed bundled default exchange rates into the database. Call once after init_database.
 *
 * # Safety
 * Database must be initialized.
 */
char *seed_exchange_rates(void);

/**
 * Update cached exchange rates from external API data.
 * `rates_json` must be a JSON array: `[{"from":"USD","to":"EUR","rate":0.92}, ...]`
 *
 * # Safety
 * `rates_json` must be a valid C string.
 */
char *update_exchange_rates(const char *rates_json);

/**
 * Set a manual exchange rate (user override — highest priority).
 *
 * # Safety
 * `from_currency` and `to_currency` must be valid C strings. `rate` is a float.
 */
char *set_manual_exchange_rate(const char *from_currency,
                               const char *to_currency,
                               double rate);

/**
 * Convert an amount between currencies using the 3-tier rate resolution.
 *
 * # Safety
 * `from_currency` and `to_currency` must be valid C strings. `amount_cents` is in cents.
 */
char *convert_currency(int64_t amount_cents,
                       const char *from_currency,
                       const char *to_currency);

/**
 * Get rate freshness info for a currency pair.
 *
 * # Safety
 * `from_currency` and `to_currency` must be valid C strings.
 */
char *get_rate_freshness(const char *from_currency,
                         const char *to_currency);

/**
 * List all exchange rates from a base currency.
 *
 * # Safety
 * `from_currency` must be a valid C string.
 */
char *list_exchange_rates(const char *from_currency);

/**
 * Search transactions with flexible filtering.
 * `filter_json` is a JSON object with optional fields:
 * - account_id (required, UUID string)
 * - query (optional, text search on description)
 * - category_id (optional, UUID string)
 * - transaction_type (optional, "income"/"expense"/"transfer")
 * - min_amount, max_amount (optional, cents)
 * - date_from, date_to (optional, RFC3339)
 * - limit, offset (optional, pagination)
 *
 * # Safety
 * `filter_json` must be a valid C string containing JSON.
 */
char *search_transactions(const char *filter_json);

/**
 * Create a new tag for a user.
 *
 * # Safety
 * All pointer parameters must be valid C strings. `color` can be null.
 */
char *create_tag(const char *user_id,
                 const char *name,
                 const char *color);

/**
 * List all tags for a user.
 *
 * # Safety
 * `user_id` must be a valid C string containing a UUID.
 */
char *list_tags(const char *user_id);

/**
 * Update a tag's name and/or color.
 * Pass JSON: {"name": "New Name", "color": "#FF5733"} — both fields are optional.
 *
 * # Safety
 * All pointer parameters must be valid C strings.
 */
char *update_tag(const char *tag_id,
                 const char *update_json);

/**
 * Delete a tag and all its transaction associations.
 *
 * # Safety
 * `tag_id` must be a valid C string containing a UUID.
 */
char *delete_tag(const char *tag_id);

/**
 * Add a tag to a transaction.
 *
 * # Safety
 * Both parameters must be valid C strings containing UUIDs.
 */
char *add_tag_to_transaction(const char *transaction_id,
                             const char *tag_id);

/**
 * Remove a tag from a transaction.
 *
 * # Safety
 * Both parameters must be valid C strings containing UUIDs.
 */
char *remove_tag_from_transaction(const char *transaction_id,
                                  const char *tag_id);

/**
 * Get all tags attached to a transaction.
 *
 * # Safety
 * `transaction_id` must be a valid C string containing a UUID.
 */
char *get_transaction_tags(const char *transaction_id);

/**
 * Get all transaction IDs that have a given tag.
 *
 * # Safety
 * `tag_id` must be a valid C string containing a UUID.
 */
char *get_transactions_by_tag(const char *tag_id);

/**
 * Get progress for all budgets in an account.
 *
 * # Safety
 * `account_id` must be a valid C string containing a UUID.
 */
char *get_all_budgets_progress(const char *account_id);

/**
 * Free a string that was allocated by the FFI layer.
 *
 * # Safety
 * `ptr` must have been returned by one of the FFI functions above.
 */
void free_string(char *ptr);

/**
 * Create a new user.
 *
 * # Safety
 * All pointer parameters must be valid C strings.
 */
char *create_user(const char *name,
                  const char *email);

/**
 * Get a user by ID.
 *
 * # Safety
 * `user_id` must be a valid C string containing a UUID.
 */
char *get_user(const char *user_id);

/**
 * List all accounts for a user.
 *
 * # Safety
 * `user_id` must be a valid C string containing a UUID.
 */
char *list_accounts(const char *user_id);

/**
 * Soft-delete an account.
 *
 * # Safety
 * `account_id` must be a valid C string containing a UUID.
 */
char *delete_account(const char *account_id);

/**
 * List all categories for a user.
 *
 * # Safety
 * `user_id` must be a valid C string containing a UUID.
 */
char *list_categories(const char *user_id);

/**
 * Soft-delete a category.
 *
 * # Safety
 * `category_id` must be a valid C string containing a UUID.
 */
char *delete_category(const char *category_id);

/**
 * Edit an existing transaction.
 *
 * # Safety
 * All pointer parameters must be valid C strings.
 */
char *edit_transaction(const char *transaction_id,
                       int64_t amount,
                       const char *transaction_type,
                       const char *description,
                       const char *category_id,
                       const char *date);

/**
 * Soft-delete a transaction.
 *
 * # Safety
 * `transaction_id` must be a valid C string containing a UUID.
 */
char *delete_transaction(const char *transaction_id);

/**
 * List transactions for an account.
 *
 * # Safety
 * `account_id` must be a valid C string containing a UUID.
 */
char *list_transactions(const char *account_id);

/**
 * List transactions for an account within a date range.
 *
 * # Safety
 * All pointer parameters must be valid C strings. Dates must be RFC3339 formatted.
 */
char *list_transactions_by_date_range(const char *account_id,
                                      const char *from,
                                      const char *to);

#endif  /* FINANCE_FFI_H */
