/* Generated by cbindgen — do not edit manually */

#ifndef FINANCE_FFI_H
#define FINANCE_FFI_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Initialize the database at the given path. Must be called before any other function.
 *
 * # Safety
 * `path` must be a valid C string pointer.
 */
char *init_database(const char *path);

/**
 * Create a new account.
 *
 * # Safety
 * All pointer parameters must be valid C strings.
 */
char *create_account(const char *user_id,
                     const char *name,
                     const char *currency);

/**
 * Create a new category.
 *
 * # Safety
 * All pointer parameters must be valid C strings.
 */
char *create_category(const char *user_id,
                      const char *name,
                      const char *icon);

/**
 * Create a new transaction.
 *
 * # Safety
 * All pointer parameters must be valid C strings.
 * `transaction_type` must be one of: "expense", "income", "transfer".
 * `amount` is in cents (integer).
 */
char *create_transaction(const char *account_id,
                         const char *category_id,
                         int64_t amount,
                         const char *transaction_type,
                         const char *description,
                         const char *date);

/**
 * Get the balance for an account (in cents).
 *
 * # Safety
 * `account_id` must be a valid C string containing a UUID.
 */
char *get_balance(const char *account_id);

/**
 * Get pending sync changes as JSON.
 */
char *get_pending_sync(void);

/**
 * Free a string that was allocated by the FFI layer.
 *
 * # Safety
 * `ptr` must have been returned by one of the FFI functions above.
 */
void free_string(char *ptr);

/**
 * Create a new user.
 *
 * # Safety
 * All pointer parameters must be valid C strings.
 */
char *create_user(const char *name,
                  const char *email);

/**
 * Get a user by ID.
 *
 * # Safety
 * `user_id` must be a valid C string containing a UUID.
 */
char *get_user(const char *user_id);

/**
 * List all accounts for a user.
 *
 * # Safety
 * `user_id` must be a valid C string containing a UUID.
 */
char *list_accounts(const char *user_id);

/**
 * Soft-delete an account.
 *
 * # Safety
 * `account_id` must be a valid C string containing a UUID.
 */
char *delete_account(const char *account_id);

/**
 * List all categories for a user.
 *
 * # Safety
 * `user_id` must be a valid C string containing a UUID.
 */
char *list_categories(const char *user_id);

/**
 * Soft-delete a category.
 *
 * # Safety
 * `category_id` must be a valid C string containing a UUID.
 */
char *delete_category(const char *category_id);

/**
 * Edit an existing transaction.
 *
 * # Safety
 * All pointer parameters must be valid C strings.
 */
char *edit_transaction(const char *transaction_id,
                       int64_t amount,
                       const char *transaction_type,
                       const char *description,
                       const char *category_id,
                       const char *date);

/**
 * Soft-delete a transaction.
 *
 * # Safety
 * `transaction_id` must be a valid C string containing a UUID.
 */
char *delete_transaction(const char *transaction_id);

/**
 * List transactions for an account.
 *
 * # Safety
 * `account_id` must be a valid C string containing a UUID.
 */
char *list_transactions(const char *account_id);

/**
 * List transactions for an account within a date range.
 *
 * # Safety
 * All pointer parameters must be valid C strings. Dates must be RFC3339 formatted.
 */
char *list_transactions_by_date_range(const char *account_id,
                                      const char *from,
                                      const char *to);

#endif  /* FINANCE_FFI_H */
